// 全部技能数据
export const SKILLS = {
  // ===== 初级 Basic =====
  slam:{name:'猛击',elem:'normal',type:'single',power:55,cooldown:1,tier:'basic',desc:'普通攻击'},
  spark:{name:'火花',elem:'fire',type:'single',power:60,cooldown:2,tier:'basic',desc:'小型火焰'},
  watergun:{name:'水枪',elem:'water',type:'single',power:60,cooldown:2,tier:'basic',desc:'水弹射击'},
  vinewhip:{name:'藤鞭',elem:'grass',type:'single',power:60,cooldown:2,tier:'basic',desc:'藤蔓抽击'},
  iceshard:{name:'冰晶',elem:'ice',type:'single',power:60,cooldown:2,tier:'basic',desc:'冰晶射出'},
  thunderbolt:{name:'雷击',elem:'electric',type:'single',power:60,cooldown:2,tier:'basic',desc:'落雷一击'},
  rockthrow:{name:'岩击',elem:'rock',type:'single',power:60,cooldown:2,tier:'basic',desc:'投掷岩石'},
  poisonsting:{name:'毒针',elem:'poison',type:'single',power:55,cooldown:2,tier:'basic',desc:'毒针攻击'},
  shadow:{name:'暗影',elem:'dark',type:'single',power:60,cooldown:2,tier:'basic',desc:'暗影突袭'},
  holylight:{name:'圣光',elem:'holy',type:'single',power:60,cooldown:2,tier:'basic',desc:'圣光照射'},
  dragonbreath:{name:'龙息',elem:'dragon',type:'single',power:65,cooldown:2,tier:'basic',desc:'龙之吐息'},
  gust:{name:'疾风',elem:'flying',type:'single',power:55,cooldown:1,tier:'basic',desc:'疾风突击'},
  ironpunch:{name:'铁拳',elem:'fight',type:'single',power:65,cooldown:2,tier:'basic',desc:'铁拳出击'},
  guard:{name:'守护',elem:'normal',type:'self',power:0,cooldown:3,tier:'basic',desc:'防御提升30%持续2回合',effect:'defUp'},
  heal:{name:'治愈',elem:'holy',type:'self',power:0,cooldown:4,tier:'basic',desc:'回复自身25%HP',effect:'heal25'},
  bite:{name:'撕咬',elem:'dark',type:'single',power:58,cooldown:1,tier:'basic',desc:'暗影撕咬'},
  tackle:{name:'冲撞',elem:'normal',type:'single',power:50,cooldown:1,tier:'basic',desc:'猛力冲撞'},

  // ===== 中级 Mid =====
  blaze:{name:'烈焰',elem:'fire',type:'single',power:90,cooldown:3,tier:'mid',desc:'强力火焰'},
  torrent:{name:'洪流',elem:'water',type:'aoe',power:70,cooldown:3,tier:'mid',desc:'洪水冲击全体'},
  overgrowth:{name:'森罗',elem:'grass',type:'aoe',power:70,cooldown:3,tier:'mid',desc:'草木蔓延全体'},
  freeze:{name:'冰封',elem:'ice',type:'single',power:85,cooldown:3,tier:'mid',desc:'冰封锁定'},
  thunder:{name:'雷霆',elem:'electric',type:'single',power:90,cooldown:3,tier:'mid',desc:'强力雷击'},
  boulder:{name:'巨岩',elem:'rock',type:'single',power:85,cooldown:3,tier:'mid',desc:'巨岩压碎'},
  venom:{name:'剧毒',elem:'poison',type:'single',power:80,cooldown:3,tier:'mid',desc:'剧毒侵蚀'},
  darkbite:{name:'暗噬',elem:'dark',type:'single',power:85,cooldown:3,tier:'mid',desc:'暗影吞噬'},
  judgment:{name:'神裁',elem:'holy',type:'single',power:90,cooldown:3,tier:'mid',desc:'神圣裁决'},
  dragonroar:{name:'龙啸',elem:'dragon',type:'aoe',power:75,cooldown:3,tier:'mid',desc:'龙啸震天'},
  hurricane:{name:'飓风',elem:'flying',type:'aoe',power:70,cooldown:3,tier:'mid',desc:'飓风席卷全体'},
  smash:{name:'碎击',elem:'fight',type:'single',power:90,cooldown:3,tier:'mid',desc:'粉碎之拳'},
  ironwall:{name:'铁壁',elem:'rock',type:'self',power:0,cooldown:4,tier:'mid',desc:'防御大幅提升',effect:'defUp2'},
  rejuvenate:{name:'回春',elem:'grass',type:'self',power:0,cooldown:5,tier:'mid',desc:'回复自身40%HP',effect:'heal40'},
  firespin:{name:'火旋',elem:'fire',type:'aoe',power:65,cooldown:3,tier:'mid',desc:'火焰旋风'},
  aquaring:{name:'水环',elem:'water',type:'self',power:0,cooldown:4,tier:'mid',desc:'持续回复HP',effect:'regen'},

  // ===== 高级 High =====
  inferno:{name:'焚天',elem:'fire',type:'aoe',power:110,cooldown:5,tier:'high',desc:'焚天之火灭世'},
  deluge:{name:'灭世洪',elem:'water',type:'aoe',power:105,cooldown:5,tier:'high',desc:'大洪水淹没'},
  verdant:{name:'万木春',elem:'grass',type:'aoe',power:100,cooldown:5,tier:'high',desc:'万木逢春'},
  absolutezero:{name:'绝对零度',elem:'ice',type:'single',power:130,cooldown:6,tier:'high',desc:'极寒冰冻'},
  megathunder:{name:'万雷',elem:'electric',type:'aoe',power:105,cooldown:5,tier:'high',desc:'雷霆万钧'},
  avalanche:{name:'山崩',elem:'rock',type:'aoe',power:100,cooldown:5,tier:'high',desc:'山崩地裂'},
  deathpoison:{name:'灭毒',elem:'poison',type:'aoe',power:95,cooldown:5,tier:'high',desc:'致命剧毒'},
  eternalnight:{name:'永夜',elem:'dark',type:'aoe',power:105,cooldown:5,tier:'high',desc:'永夜降临'},
  divinepunish:{name:'天罚',elem:'holy',type:'aoe',power:110,cooldown:5,tier:'high',desc:'天罚降世'},
  dragondescent:{name:'龙神降',elem:'dragon',type:'single',power:140,cooldown:6,tier:'high',desc:'龙神降世'},
  skyascend:{name:'天翔',elem:'flying',type:'single',power:120,cooldown:5,tier:'high',desc:'天翔万里'},
  heavenbreak:{name:'破天',elem:'fight',type:'single',power:135,cooldown:6,tier:'high',desc:'破天一击'},
  allheal:{name:'万象回春',elem:'holy',type:'ally_all',power:0,cooldown:6,tier:'high',desc:'全队回复30%HP',effect:'healAll30'},
  soulburn:{name:'焚魂',elem:'dark',type:'single',power:120,cooldown:5,tier:'high',desc:'灼烧灵魂'}
};
